load_col:
    inter: [user_id, item_id, timestamp]
    item: ['item_id','title','sales_rank','price','brand','categories','sales_type']
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id


# SASRec
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: "gelu"
layer_norm_eps: 1e-12
initializer_range: 0.02
initializer_weight: [0.1, 1.0, 1.0]
loss_type: "CE"



# Representation MoE
expert_num: 4
gate_selection: softmax
start_expert_num: 4
start_gate_selection: softmax
# Temporal MoE
temporal_expert_num: 4
temporal_gate_selection: softmax
interval_scale: 100


# ------------
expert_type: 'ffn'
share_moe: True

moe_topk: 6
shared_expert_nums: 1
routed_expert_nums: 8
pretrained_embedding: True


# ID Contrast Learning
temperature: 0.1
# Placeholder Contrast Learning
beta: 0.2
phcl_temperature: 1.0
phcl_weight: 1.0
time_scale: 15000000

n_clusters: 100
time_span: 200

diversity_weight: 0.9

wavelet_J: 4

cosine_lambda: 1.0
